import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/app/global/shadcn/components/ui/sidebar"
import { AppSidebar } from "@/app/global/shadcn/components/app-sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-screen min-h-screen">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </body>
      </html>
  );
}
